[package]
name = "matasano"
version = "0.0.1"
authors = ["Jesse Luehrs <doy@tozt.net>"]

[[test]]
name = "all"
path = "tests/lib.rs"

[dependencies]
rustc-serialize = "0.3"
openssl = "0.5"
rand = "0.3"
time = "0.1"
